version: 0.2

phases:
  build:
    commands:
      - echo Entrando no build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build Finalizado com sucesso
artifacts:
  files:
    - target/bank-account-api-0.0.1-SNAPSHOT.jar
  discard-paths: yes