create table account (id integer not null auto_increment, account_code varchar(255) not null, agency_code varchar(255) not null, name_owner varchar(255) not null, verification_digital varchar(255) not null, primary key (id)) engine=MyISAM;
create table card (id integer not null auto_increment, digit_code varchar(255) not null, flag integer not null, limit_balance decimal(22,2) not null, name varchar(255) not null, number varchar(255) not null, type_id integer not null, card_id integer, primary key (id)) engine=MyISAM;
create table roles (id bigint not null auto_increment, name varchar(20), primary key (id)) engine=MyISAM;
create table type (id integer not null auto_increment, type_card integer not null, primary key (id)) engine=MyISAM;
create table user (id bigint not null auto_increment, password varchar(255), username varchar(255), primary key (id)) engine=MyISAM;
create table user_roles (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=MyISAM;
alter table card add constraint FKj1b7aqkhy8ls3d6if9aqj63p8 foreign key (type_id) references type (id);
alter table card add constraint FK319twdsf0l9hk222n8vkt40pc foreign key (card_id) references account (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
