create table account (
    id integer generated by default as identity,
    account_code varchar(255) not null,
    agency_code varchar(255) not null,
    name_owner varchar(255) not null,
    verification_digital varchar(255) not null,
    primary key (id)
);

create table card (
    id integer generated by default as identity,
    digit_code varchar(255) not null,
    flag integer not null,
    limit_balance decimal(22,2) not null,
    name varchar(255) not null,
    number varchar(255) not null,
    tyoe_id integer not null,
    card_id integer,
    primary key (id)
);

create table type (
    id integer generated by default as identity,
    type_card integer not null,
    primary key (id)
);

alter table card add constraint FK3fmdud3fhfedkvm1j3cg9dt2d foreign key (tyoe_id) references type;

alter table card add constraint FK319twdsf0l9hk222n8vkt40pc foreign key (card_id) references account;
